title: New Math
author: Peter Osudar
email: peter.osudar@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  An interesting way to get more comfortable with GitHub and making a portfolio.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
